//sword of the cosmos
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_sword>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_sword>, [[null, null, null, null, null, null, null, <ore:ingotInfinity>, <draconicadditions:chaotic_staff_of_power>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, <ore:ingotCrystalMatrix>, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, null, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotCrystalMatrix>, null, null, null, null], [<avaritia:resource:5>, null, null, null, null, null, null, null, null]]);

//endest pearl
mods.avaritia.ExtremeCrafting.remove(<avaritia:endest_pearl>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:endest_pearl>, [[null, null, null, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, null, null, null], [null, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, <ore:manaPearl>, <ore:enderpearl>, <ore:manaPearl>, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, null], [null, <ore:ingotStellarAlloy>, <ore:enderpearl>, <darkutils:material:1>, <rftools:infused_enderpearl>, <darkutils:material:1>, <ore:enderpearl>, <ore:ingotStellarAlloy>, null], [<ore:ingotStellarAlloy>, <ore:manaPearl>, <darkutils:material:1>, <ore:pearlFluix>, <ore:ingotCosmicNeutronium>, <ore:pearlFluix>, <darkutils:material:1>, <ore:manaPearl>, <ore:ingotStellarAlloy>], [<ore:ingotStellarAlloy>, <ore:enderpearl>, <rftools:infused_enderpearl>, <ore:ingotCosmicNeutronium>, <ore:netherStar>, <ore:ingotCosmicNeutronium>, <rftools:infused_enderpearl>, <ore:enderpearl>, <ore:ingotStellarAlloy>], [<ore:ingotStellarAlloy>, <ore:manaPearl>, <darkutils:material:1>, <ore:pearlFluix>, <ore:ingotCosmicNeutronium>, <ore:pearlFluix>, <darkutils:material:1>, <ore:manaPearl>, <ore:ingotStellarAlloy>], [null, <ore:ingotStellarAlloy>, <ore:enderpearl>, <darkutils:material:1>, <rftools:infused_enderpearl>, <darkutils:material:1>, <ore:enderpearl>, <ore:ingotStellarAlloy>, null], [null, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, <ore:manaPearl>, <ore:enderpearl>, <ore:manaPearl>, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, null], [null, null, null, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, <ore:ingotStellarAlloy>, null, null, null]]);

//ultimate stew
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);

mods.extendedcrafting.TableCrafting.addShapeless(0, <avaritia:ultimate_stew>*9, [<avaritia:resource:2>, <ore:cropWheat>, <ore:cropCarrot>, <ore:cropBeet>, <ore:cropPotato>, <ore:cropApple>, <minecraft:melon>, <ore:cropPumpkin>, <ore:cropCactus>, <minecraft:brown_mushroom>, <minecraft:red_mushroom>, <ore:cropCherry>, <ore:cropBlackberry>, <ore:cropRaspberry>, <ore:cropBlueberry>, <ore:cropPear>, <ore:cropRice>, <ore:cropBellpepper>, <ore:cropCoffee>, <ore:cropBarley>, <ore:cropBean>, <ore:cropPeach>, <ore:cropGrape>, <ore:cropFlax>, <ore:cropMaloberry>, <ore:cropKenaf>, <ore:cropLemon>, <ore:cropScallion>, <ore:cropCucumber>, <ore:cropParsnip>, <ore:cropCassava>, <ore:cropCelery>, <ore:cropPlum>, <ore:cropOkra>, <ore:cropOrange>, <ore:cropCashew>, <ore:cropCoconut>, <ore:cropDragonfruit>, <ore:cropBroccoli>, <ore:cropSunflower>, <ore:cropMaplesyrup>, <ore:cropCanola>, <ore:cropMulberry>, <ore:cropElderberry>, <ore:cropAlmond>, <ore:cropCantaloupe>, <ore:cropChilipepper>, <ore:cropBlightberry>, <ore:cropAsparagus>, <ore:cropLettuce>, <ore:cropPeas>, <ore:cropCabbage>, <ore:cropSweetpotato>, <ore:cropSesame>, <ore:cropGinger>, <ore:cropGarlic>, <ore:cropRadish>, <ore:cropSisal>, <ore:cropPineapple>, <ore:cropCurryleaf>, <ore:cropJuniperberry>, <ore:cropStrawberry>, <ore:cropTomato>, <ore:cropVanillabean>, <ore:cropGrapefruit>, <ore:cropOnion>, <ore:cropDuskberry>, <ore:cropZucchini>, <ore:cropKiwi>, <ore:cropWintersquash>, <ore:cropPistachio>, <ore:cropCorn>, <ore:cropCranberry>, <ore:cropWalnut>, <ore:cropLime>, <ore:cropPomegranate>, <ore:cropCandleberry>, <ore:cropLeek>, <ore:cropSpinach>, <ore:cropPeppercorn>, <ore:cropTomatillo>]);

//crystaltine ingot
mods.extendedcrafting.TableCrafting.remove(<extendedcrafting:material:24>);

mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:material:24>, [[<ore:manaDiamond>, <mysticalagriculture:aluminum_seeds>, <contenttweaker:neutral_steel_6>, <moreplates:awakened_draconium_plate>, <contenttweaker:neutral_steel_6>, <mysticalagriculture:aluminum_seeds>, <ore:manaDiamond>], [<moreplates:awakened_draconium_plate>, <ore:ingotCrystallineAlloy>, <mysticalagriculture:aluminum_seeds>, null, <mysticalagriculture:aluminum_seeds>, <ore:ingotCrystallineAlloy>, <moreplates:awakened_draconium_plate>], [<ore:crystalOsmium>, <ore:crystalPureFluix>, <ore:ingotCrystallineAlloy>, <ore:ingotCrystallineAlloy>, <ore:ingotCrystallineAlloy>, <ore:crystalPureFluix>, <ore:crystalOsmium>], [<moreplates:awakened_draconium_plate>, <ore:ingotCrystallineAlloy>, <mysticalagriculture:aluminum_seeds>, null, <mysticalagriculture:aluminum_seeds>, <ore:ingotCrystallineAlloy>, <moreplates:awakened_draconium_plate>], [<ore:manaDiamond>, <mysticalagriculture:aluminum_seeds>, <contenttweaker:neutral_steel_6>, <moreplates:awakened_draconium_plate>, <contenttweaker:neutral_steel_6>, <mysticalagriculture:aluminum_seeds>, <ore:manaDiamond>], [null, null, null, null, null, null, null], [null, null, null, null, null, null, null]]);

//infinity ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:6>, [[<ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>], [<ore:ingotUltimate>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <ore:ingotUltimate>], [<moreplates:awakened_draconium_plate>, <moreplates:awakened_draconium_plate>, <avaritia:resource:5>, <avaritia:resource:5>, <moreplates:awakened_draconium_plate>, <avaritia:resource:5>, <avaritia:resource:5>, <moreplates:awakened_draconium_plate>, <moreplates:awakened_draconium_plate>], [<ore:ingotUltimate>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <ore:ingotUltimate>], [<ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);

//crystal matrix ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:1>, [[<avaritia:resource>, <ore:runeSummerB>, <draconicevolution:draconic_core>, <moreplates:awakened_draconium_plate>, <avaritia:resource>, <moreplates:awakened_draconium_plate>, <draconicevolution:draconic_core>, <ore:runeSummerB>, <avaritia:resource>], [<moreplates:awakened_draconium_plate>, <moreplates:awakened_draconium_plate>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <actuallyadditions:item_crystal_empowered:5>, <moreplates:awakened_draconium_plate>, <moreplates:awakened_draconium_plate>], [<ore:runeSummerB>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <draconicevolution:draconic_core>, <actuallyadditions:item_crystal_empowered:5>, <draconicevolution:draconic_core>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:runeSummerB>], [<moreplates:awakened_draconium_plate>, <moreplates:awakened_draconium_plate>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <actuallyadditions:item_crystal_empowered:5>, <moreplates:awakened_draconium_plate>, <moreplates:awakened_draconium_plate>], [<avaritia:resource>, <ore:runeSummerB>, <draconicevolution:draconic_core>, <moreplates:awakened_draconium_plate>, <avaritia:resource>, <moreplates:awakened_draconium_plate>, <draconicevolution:draconic_core>, <ore:runeSummerB>, <avaritia:resource>], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);

//ultimate ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:material:32>, [[<ore:ingotManyullyn>, <moreplates:awakened_draconium_plate>, <botania:quartztypemana>, <botania:quartztypesunny>, <botania:quartztypered>, <botania:quartztypesunny>, <botania:quartztypemana>, <moreplates:awakened_draconium_plate>, <ore:ingotManyullyn>], [<moreplates:awakened_draconium_plate>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <botania:quartztypeelf>, <botania:quartztypelavender>, <botania:quartztypeelf>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <moreplates:awakened_draconium_plate>], [<tconstruct:ingots:2>, <botania:quartztypered>, <botania:quartztypelavender>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <botania:quartztypelavender>, <botania:quartztypered>, <tconstruct:ingots:2>], [<moreplates:awakened_draconium_plate>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <botania:quartztypeelf>, <botania:quartztypelavender>, <botania:quartztypeelf>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <moreplates:awakened_draconium_plate>], [<ore:ingotManyullyn>, <moreplates:awakened_draconium_plate>, <botania:quartztypemana>, <botania:quartztypesunny>, <botania:quartztypered>, <botania:quartztypesunny>, <botania:quartztypemana>, <moreplates:awakened_draconium_plate>, <ore:ingotManyullyn>], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);

//neutronium compressor
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);

//infinity ingot
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);

//neutron collector
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);

//Crystal matrix
recipes.remove(<avaritia:resource:1>);

//planet eater
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_shovel>, [[null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null], [<ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null, null]]);

//World Breaker
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_pickaxe>, [[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotInfinity>, null, null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//hoe of green earth
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_hoe>, [[null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null]]);

//longbow of the heavens
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_bow>, [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:blockCrystalMatrix>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null]]);

//skullfire sword
mods.avaritia.ExtremeCrafting.remove(<avaritia:skullfire_sword>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:skullfire_sword>, [[null, null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>], [null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>], [null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null], [null, <ore:bone>, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null], [null, null, <ore:bone>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null, null], [null, null, <ore:logWood>, <ore:bone>, null, null, null, null, null], [null, <ore:logWood>, null, null, <ore:bone>, null, null, null, null], [<ore:netherStar>, null, null, null, null, null, null, null, null]]);

//nature's ruin
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_axe>, [[null, null, null, <ore:ingotInfinity>, null, null, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null]]);

// Infinity Helmet
recipes.remove(<avaritia:infinity_helmet>);
mods.avaritia.ExtremeCrafting.addShaped(4, <avaritia:infinity_helmet> * 1, [[null, null, null, null, null, null, null, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, null, <avaritia:resource:5>, null, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <draconicevolution:draconic_helm>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, null, <avaritia:resource:6>, null, <avaritia:resource:6>, null, <avaritia:resource:4>, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Infinity Breastplate
recipes.remove(<avaritia:infinity_chestplate>);
mods.avaritia.ExtremeCrafting.addShaped(4, <avaritia:infinity_chestplate> * 1, [[null, <avaritia:resource:4>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:4>, null], [<avaritia:block_resource:2>, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:block_resource:2>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:block_resource:2>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:block_resource:2>, <draconicevolution:draconic_chest>, <avaritia:block_resource:2>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:block_resource:2>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null]]);

// Infinity Leggings
recipes.remove(<avaritia:infinity_pants>);
mods.avaritia.ExtremeCrafting.addShaped(4, <avaritia:infinity_pants> * 1, [[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>], [<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <draconicevolution:draconic_legs>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:block_resource:2>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:block_resource:2>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>]]);

// Infinity Boots
recipes.remove(<avaritia:infinity_boots>);
mods.avaritia.ExtremeCrafting.addShaped(4, <avaritia:infinity_boots> * 1, [[null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null], [null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null],[null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, null],[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <draconicevolution:draconic_boots>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Pile of Neutrons
recipes.remove(<avaritia:resource:2>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:2>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:2> * 1, [[<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <minecraft:coal_block>, <minecraft:coal_block>, <minecraft:coal_block>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>], [<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <minecraft:coal_block>, <minecraft:coal_block>, <bewitchment:bottle_of_vampire_blood>, <minecraft:coal_block>, <minecraft:coal_block>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>],[<mysticalagriculture:coal_essence>, <minecraft:coal_block>, <minecraft:coal_block>, <vampirism:vampire_blood_bottle>, <xreliquary:emperor_chalice>, <vampirism:vampire_blood_bottle>, <minecraft:coal_block>, <minecraft:coal_block>, <mysticalagriculture:coal_essence>],[<minecraft:coal_block>, <minecraft:coal_block>, <vampirism:vampire_blood_bottle>, <minecraft:coal_block>, <vampirism:weak_human_heart>, <minecraft:coal_block>, <vampirism:vampire_blood_bottle>, <minecraft:coal_block>, <minecraft:coal_block>],[<minecraft:coal_block>, <bewitchment:bottle_of_blood>, <xreliquary:emperor_chalice>, <bewitchment:heart>, <avaritia:block_resource:2>, <bewitchment:demon_heart>, <xreliquary:emperor_chalice>, <bewitchment:bottle_of_blood>, <minecraft:coal_block>],[<minecraft:coal_block>, <minecraft:coal_block>, <vampirism:vampire_blood_bottle>, <minecraft:coal_block>, <cyberware:body_part:2>, <minecraft:coal_block>, <vampirism:vampire_blood_bottle>, <minecraft:coal_block>, <minecraft:coal_block>],[<mysticalagriculture:coal_essence>, <minecraft:coal_block>, <minecraft:coal_block>, <vampirism:vampire_blood_bottle>, <xreliquary:emperor_chalice>, <vampirism:vampire_blood_bottle>, <minecraft:coal_block>, <minecraft:coal_block>, <mysticalagriculture:coal_essence>],[<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <minecraft:coal_block>, <minecraft:coal_block>, <bewitchment:bottle_of_vampire_blood>, <minecraft:coal_block>, <minecraft:coal_block>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>],[<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <minecraft:coal_block>, <minecraft:coal_block>, <minecraft:coal_block>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>]]);

// Neutronium Ingot
recipes.remove(<avaritia:resource:4>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:4> * 1, [[<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <moreplates:coal_plate>, <moreplates:coal_plate>, <moreplates:coal_plate>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>], [<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <moreplates:coal_plate>, <moreplates:coal_plate>, <moreplates:evil_infused_iron_gear>, <moreplates:coal_plate>, <moreplates:coal_plate>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>],[<mysticalagriculture:coal_essence>, <moreplates:coal_plate>, <betteranimalsplus:wolf_pelt_black>, <avaritia:resource:3>, <torchmaster:frozen_pearl>, <avaritia:resource:3>, <betteranimalsplus:bearhead_2>, <moreplates:coal_plate>, <mysticalagriculture:coal_essence>],[<moreplates:coal_plate>, <moreplates:coal_plate>, <avaritia:resource:3>, <vampirism:human_heart>, <darkutils:material:1>, <vampirism:human_heart>, <avaritia:resource:3>, <moreplates:coal_plate>, <moreplates:coal_plate>],[<moreplates:coal_plate>, <moreplates:evil_infused_iron_gear>, <torchmaster:frozen_pearl>, <darkutils:material:1>, <vampirism:soul_orb_vampire>, <darkutils:material:1>, <torchmaster:frozen_pearl>, <moreplates:evil_infused_iron_gear>, <moreplates:coal_plate>],[<moreplates:coal_plate>, <moreplates:coal_plate>, <avaritia:resource:3>, <vampirism:human_heart>, <darkutils:material:1>, <vampirism:human_heart>, <avaritia:resource:3>, <moreplates:coal_plate>, <moreplates:coal_plate>],[<mysticalagriculture:coal_essence>, <moreplates:coal_plate>, <betteranimalsplus:wolfhead_1>, <avaritia:resource:3>, <torchmaster:frozen_pearl>, <avaritia:resource:3>, <betteranimalsplus:bear_skin_black>, <moreplates:coal_plate>, <mysticalagriculture:coal_essence>],[<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <moreplates:coal_plate>, <moreplates:coal_plate>, <moreplates:evil_infused_iron_gear>, <moreplates:coal_plate>, <moreplates:coal_plate>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>],[<mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <moreplates:coal_plate>, <moreplates:coal_plate>, <moreplates:coal_plate>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>]]);

// Neutronium Nugget
recipes.remove(<avaritia:resource:3>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:3> * 1, [[<avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>], [<avaritia:resource:2>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>],[<avaritia:resource:2>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <botania:flower:15>, <avaritia:resource:2>, <botania:flower:15>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>],[<avaritia:resource:2>, <mysticalagriculture:coal_essence>, <botania:flower:15>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <botania:flower:15>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>],[<avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <extendedcrafting:singularity:0>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>],[<avaritia:resource:2>, <mysticalagriculture:coal_essence>, <botania:flower:15>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <botania:flower:15>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>],[<avaritia:resource:2>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <botania:flower:15>, <avaritia:resource:2>, <botania:flower:15>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>],[<avaritia:resource:2>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <mysticalagriculture:coal_essence>, <avaritia:resource:2>],[<avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>]]);
