// Cosmic Meatballs
recipes.remove(<avaritia:cosmic_meatballs>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:cosmic_meatballs> * 12, [[null, null, null, null, <avaritia:resource:4>, null, null, null, null], [null, null, null, null, <betteranimalsplus:antler>, null, null, null, null],[null, null, <animania:cheese_mold>, <animania:milk_bottle>, <harvestcraft:charrrawitem>, <animania:milk_bottle>, <animania:holstein_cheese_wheel>, null, null],[null, null, <animania:milk_bottle>, <betteranimalsplus:pheasantraw>, <harvestcraft:anchovyrawitem>, <betteranimalsplus:eel_meat_raw>, <animania:milk_bottle>, null, null],[<avaritia:resource:4>, <betteranimalsplus:antler>, <harvestcraft:tunarawitem>, <harvestcraft:perchrawitem>, <avaritia:resource:4>, <harvestcraft:catfishrawitem>, <harvestcraft:snapperrawitem>, <betteranimalsplus:antler>, <avaritia:resource:4>],[null, null, <animania:milk_bottle>, <betteranimalsplus:venisonraw>, <harvestcraft:carprawitem>, <betteranimalsplus:turkey_leg_raw>, <animania:milk_bottle>, null, null],[null, null, <animania:goat_cheese_wheel>, <animania:milk_bottle>, <harvestcraft:mudfishrawitem>, <animania:milk_bottle>, <animania:friesian_cheese_wheel>, null, null],[null, null, null, null, <betteranimalsplus:antler>, null, null, null, null],[null, null, null, null, <avaritia:resource:4>, null, null, null, null]]);

// Infinity Catalyst
recipes.remove(<avaritia:resource:5>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:5> * 1, [[null, null, null, null, <avaritia:block_resource:0>, null, null, null, null], [null, <avaritia:block_resource:0>, null, null, <avaritia:ultimate_stew>, null, null, <avaritia:block_resource:0>, null],[null, null, <torchmaster:frozen_pearl>, <vampirism:vampire_blood_bottle>, <avaritia:cosmic_meatballs>, <vampirism:vampire_blood_bottle>, <torchmaster:frozen_pearl>, null, null],[null, null, <vampirism:vampire_blood_bottle>, <avaritia:block_resource:2>, <avaritia:endest_pearl>, <avaritia:block_resource:2>, <vampirism:vampire_blood_bottle>, null, null],[<avaritia:block_resource:0>, <avaritia:ultimate_stew>, <avaritia:cosmic_meatballs>, <avaritia:endest_pearl>, <extendedcrafting:singularity_ultimate>, <avaritia:endest_pearl>, <avaritia:cosmic_meatballs>, <avaritia:ultimate_stew>, <avaritia:block_resource:0>],[null, null, <vampirism:vampire_blood_bottle>, <avaritia:block_resource:2>, <avaritia:endest_pearl>, <avaritia:block_resource:2>, <vampirism:vampire_blood_bottle>, null, null],[null, null, <torchmaster:frozen_pearl>, <vampirism:vampire_blood_bottle>, <avaritia:cosmic_meatballs>, <vampirism:vampire_blood_bottle>, <torchmaster:frozen_pearl>, null, null],[null, <avaritia:block_resource:0>, null, null, <avaritia:ultimate_stew>, null, null, <avaritia:block_resource:0>, null],[null, null, null, null, <avaritia:block_resource:0>, null, null, null, null]]);

// Neutronium Block
recipes.remove(<avaritia:block_resource:0>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:block_resource:0>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:block_resource:0> * 1, [[<moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>], [<avaritia:resource:4>, <moreplates:neutronium_gear>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <moreplates:neutronium_gear>, <avaritia:resource:4>],[<moreplates:neutronium_plate>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <darkutils:material:1>, <extrautils2:unstableingots:2>, <darkutils:material:1>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <moreplates:neutronium_plate>],[<avaritia:resource:4>, <extrautils2:compressedcobblestone:7>, <darkutils:material:1>, <extrautils2:compressedcobblestone:7>, <extendedcrafting:singularity:0>, <extrautils2:compressedcobblestone:7>, <darkutils:material:1>, <extrautils2:compressedcobblestone:7>, <avaritia:resource:4>],[<moreplates:neutronium_plate>, <extrautils2:compressedcobblestone:7>, <extrautils2:unstableingots:2>, <extendedcrafting:singularity:0>, <extrautils2:compressedcobblestone:7>, <extendedcrafting:singularity:0>, <extrautils2:unstableingots:2>, <extrautils2:compressedcobblestone:7>, <moreplates:neutronium_plate>],[<avaritia:resource:4>, <extrautils2:compressedcobblestone:7>, <darkutils:material:1>, <extrautils2:compressedcobblestone:7>, <extendedcrafting:singularity:0>, <extrautils2:compressedcobblestone:7>, <darkutils:material:1>, <extrautils2:compressedcobblestone:7>, <avaritia:resource:4>],[<moreplates:neutronium_plate>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <darkutils:material:1>, <extrautils2:unstableingots:2>, <darkutils:material:1>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <moreplates:neutronium_plate>],[<avaritia:resource:4>, <moreplates:neutronium_gear>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <extrautils2:compressedcobblestone:7>, <moreplates:neutronium_gear>, <avaritia:resource:4>],[<moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>, <avaritia:resource:4>, <moreplates:neutronium_plate>]]);

// Unstable Ender Pearl
recipes.remove(<darkutils:material:1>);
mods.extendedcrafting.TableCrafting.addShaped(4, <darkutils:material:1> * 1, [[null, null, null, <darkutils:wither_block:0>, <darkutils:wither_block:0>, <darkutils:wither_block:0>, null, null, null], [null, null, <darkutils:wither_block:0>, <darkutils:wither_block:0>, <vampirism:blood_bottle:9>, <darkutils:wither_block:0>, <darkutils:wither_block:0>, null, null],[null, <darkutils:wither_block:0>, <vampirism:blood_bottle:9>, <torchmaster:frozen_pearl>, <minecraft:dragon_breath>, <torchmaster:frozen_pearl>, <vampirism:blood_bottle:9>, <darkutils:wither_block:0>, null],[<darkutils:wither_block:0>, <darkutils:wither_block:0>, <torchmaster:frozen_pearl>, <minecraft:dragon_egg>, <bewitchment:scorned_brick_lilith_statue>, <minecraft:dragon_egg>, <torchmaster:frozen_pearl>, <darkutils:wither_block:0>, <darkutils:wither_block:0>],[<darkutils:wither_block:0>, <vampirism:blood_bottle:9>, <minecraft:dragon_breath>, <bewitchment:scorned_brick_herne_statue>, <xreliquary:salamander_eye>, <bewitchment:scorned_brick_moloch_statue>, <minecraft:dragon_breath>, <vampirism:blood_bottle:9>, <darkutils:wither_block:0>],[<darkutils:wither_block:0>, <darkutils:wither_block:0>, <torchmaster:frozen_pearl>, <minecraft:dragon_egg>, <bewitchment:scorned_brick_baphomet_statue>, <minecraft:dragon_egg>, <torchmaster:frozen_pearl>, <darkutils:wither_block:0>, <darkutils:wither_block:0>],[null, <darkutils:wither_block:0>, <vampirism:blood_bottle:9>, <torchmaster:frozen_pearl>, <minecraft:dragon_breath>, <torchmaster:frozen_pearl>, <vampirism:blood_bottle:9>, <darkutils:wither_block:0>, null],[null, null, <darkutils:wither_block:0>, <darkutils:wither_block:0>, <vampirism:blood_bottle:9>, <darkutils:wither_block:0>, <darkutils:wither_block:0>, null, null],[null, null, null, <darkutils:wither_block:0>, <darkutils:wither_block:0>, <darkutils:wither_block:0>, null, null, null]]);

// Frozen Pearl
recipes.remove(<torchmaster:frozen_pearl>);
mods.avaritia.ExtremeCrafting.remove(<torchmaster:frozen_pearl>);
mods.extendedcrafting.TableCrafting.addShaped(4, <torchmaster:frozen_pearl>, [[<mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <botania:manaresource:0>, <botania:manaresource:0>, <botania:manaresource:0>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>], [<mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <botania:manaresource:0>, <moreplates:manasteel_gear>, <xreliquary:mob_ingredient:10>, <moreplates:manasteel_gear>, <botania:manaresource:0>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>],[<mysticalagriculture:ice_essence>, <botania:manaresource:0>, <moreplates:manasteel_gear>, <botania:manaresource:1>, <avaritia:resource:0>, <botania:manaresource:1>, <moreplates:manasteel_gear>, <botania:manaresource:0>, <mysticalagriculture:ice_essence>],[<botania:manaresource:0>, <moreplates:manasteel_gear>, <botania:manaresource:1>, <botania:manaresource:2>, <xreliquary:mob_ingredient:10>, <botania:manaresource:2>, <botania:manaresource:1>, <moreplates:manasteel_gear>, <botania:manaresource:0>],[<botania:manaresource:0>, <xreliquary:mob_ingredient:10>, <avaritia:resource:0>, <xreliquary:mob_ingredient:10>, <enderio:item_soul_vial>, <xreliquary:mob_ingredient:10>, <avaritia:resource:0>, <xreliquary:mob_ingredient:10>, <botania:manaresource:0>],[<botania:manaresource:0>, <moreplates:manasteel_gear>, <botania:manaresource:1>, <botania:manaresource:2>, <xreliquary:mob_ingredient:10>, <botania:manaresource:2>, <botania:manaresource:1>, <moreplates:manasteel_gear>, <botania:manaresource:0>],[<mysticalagriculture:ice_essence>, <botania:manaresource:0>, <moreplates:manasteel_gear>, <botania:manaresource:1>, <avaritia:resource:0>, <botania:manaresource:1>, <moreplates:manasteel_gear>, <botania:manaresource:0>, <mysticalagriculture:ice_essence>],[<mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <botania:manaresource:0>, <moreplates:manasteel_gear>, <xreliquary:mob_ingredient:10>, <moreplates:manasteel_gear>, <botania:manaresource:0>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>],[<mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <botania:manaresource:0>, <botania:manaresource:0>, <botania:manaresource:0>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>, <mysticalagriculture:ice_essence>]]);

recipes.remove(<avaritia:neutron_collector>);

